version: '3.1'

services:

  db:
    build:
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
      - ./src/db/scripts:/docker-entrypoint-initdb.d
